import { Category, CategoryType } from './category.entity';

const staticDate = new Date('2025-08-01T00:00:00.000Z');

export const CATEGORIES: Category[] = [
  // Income categories
  {
    id: 1,
    name: 'salary',
    type: CategoryType.INCOME,
    icon: 'money-bill',
    background: '#4CAF50',
    createdAt: staticDate,
    updatedAt: staticDate,
  },
  {
    id: 2,
    name: 'freelance',
    type: CategoryType.INCOME,
    icon: 'briefcase',
    background: '#2196F3',
    createdAt: staticDate,
    updatedAt: staticDate,
  },
  {
    id: 3,
    name: 'investment',
    type: CategoryType.INCOME,
    icon: 'chart-line',
    background: '#FF9800',
    createdAt: staticDate,
    updatedAt: staticDate,
  },
  {
    id: 4,
    name: 'bonus',
    type: CategoryType.INCOME,
    icon: 'gift',
    background: '#9C27B0',
    createdAt: staticDate,
    updatedAt: staticDate,
  },
  {
    id: 5,
    name: 'rental',
    type: CategoryType.INCOME,
    icon: 'home',
    background: '#607D8B',
    createdAt: staticDate,
    updatedAt: staticDate,
  },
  {
    id: 6,
    name: 'other income',
    type: CategoryType.INCOME,
    icon: 'dollar-sign',
    background: '#795548',
    createdAt: staticDate,
    updatedAt: staticDate,
  },

  // Expense categories
  {
    id: 7,
    name: 'food',
    type: CategoryType.EXPENSE,
    icon: 'utensils',
    background: '#F44336',
    createdAt: staticDate,
    updatedAt: staticDate,
  },
  {
    id: 8,
    name: 'transport',
    type: CategoryType.EXPENSE,
    icon: 'car',
    background: '#9C27B0',
    createdAt: staticDate,
    updatedAt: staticDate,
  },
  {
    id: 9,
    name: 'entertainment',
    type: CategoryType.EXPENSE,
    icon: 'film',
    background: '#E91E63',
    createdAt: staticDate,
    updatedAt: staticDate,
  },
  {
    id: 10,
    name: 'shopping',
    type: CategoryType.EXPENSE,
    icon: 'shopping-bag',
    background: '#FF5722',
    createdAt: staticDate,
    updatedAt: staticDate,
  },
  {
    id: 11,
    name: 'health',
    type: CategoryType.EXPENSE,
    icon: 'heart',
    background: '#00BCD4',
    createdAt: staticDate,
    updatedAt: staticDate,
  },
  {
    id: 12,
    name: 'education',
    type: CategoryType.EXPENSE,
    icon: 'book',
    background: '#3F51B5',
    createdAt: staticDate,
    updatedAt: staticDate,
  },
  {
    id: 13,
    name: 'utilities',
    type: CategoryType.EXPENSE,
    icon: 'bolt',
    background: '#FFC107',
    createdAt: staticDate,
    updatedAt: staticDate,
  },
  {
    id: 14,
    name: 'travel',
    type: CategoryType.EXPENSE,
    icon: 'plane',
    background: '#8BC34A',
    createdAt: staticDate,
    updatedAt: staticDate,
  },
  {
    id: 15,
    name: 'other expense',
    type: CategoryType.EXPENSE,
    icon: 'credit-card',
    background: '#9E9E9E',
    createdAt: staticDate,
    updatedAt: staticDate,
  },
];
